export const products = [
  {
    id: 1,
    name: "keyboard magic",
    image: require("../Assets/keyboard/images.jpg"),
    category: "keyboard",
    price: 560000,
  },
  {
    id: 2,
    name: "keyboard sutra",
    image: require("../Assets/keyboard/images1.jpg"),
    category: "keyboard",
    price: 760000,
  },
  {
    id: 3,
    name: "keyboard durex",
    image: require("../Assets/keyboard/images2.jpg"),
    category: "keyboard",
    price: 5060000,
  },
  {
    id: 4,
    name: "keyboard dragon",
    image: require("../Assets/keyboard/images3.jpg"),
    category: "keyboard",
    price: 5890000,
  },
  {
    id: 5,
    name: "keyboard butter",
    image: require("../Assets/keyboard/images4.jpg"),
    category: "keyboard",
    price: 590000,
  },
  {
    id: 6,
    name: "Macbook",
    image: require("../Assets/matchine/images0.jpg"),
    category: "personal computer",
    price: 20000000,
  },
  {
    id: 7,
    name: "Macbook pro",
    image: require("../Assets/matchine/images1.jpg"),
    category: "personal computer",
    price: 24000000,
  },
  {
    id: 8,
    name: "microsoft",
    image: require("../Assets/matchine/images2.jpg"),
    category: "personal computer",
    price: 5600000,
  },
  {
    id: 9,
    name: "officer",
    image: require("../Assets/matchine/images3.jpg"),
    category: "personal computer",
    price: 5900000,
  },
  {
    id: 10,
    name: "yoga computer",
    image: require("../Assets/matchine/images4.jpg"),
    category: "personal computer",
    price: 18000000,
  },
  {
    id: 11,
    name: "monitor hp",
    image: require("../Assets/monitor/images.jpg"),
    category: "monitor",
    price: 5600000,
  },
  {
    id: 12,
    name: "mi monitor",
    image: require("../Assets/monitor/images1.jpg"),
    category: "monitor",
    price: 5000000,
  },
  {
    id: 13,
    name: "dual monitor",
    image: require("../Assets/monitor/images2.jpg"),
    category: "monitor",
    price: 10000000,
  },
  {
    id: 14,
    name: "gaming monitor",
    image: require("../Assets/monitor/images3.jpg"),
    category: "monitor",
    price: 18000000,
  },
  {
    id: 15,
    name: "sumsang monitor",
    image: require("../Assets/monitor/images4.jpg"),
    category: "monitor",
    price: 5600000,
  },
  {
    id: 16,
    name: "touch pad win B",
    image: require("../Assets/cursorcontroller/images.jpg"),
    category: "Cursor Controller",
    price: 900000,
  },
  {
    id: 17,
    name: "apple magic pad",
    image: require("../Assets/cursorcontroller/images1.jpg"),
    category: "Cursor Controller",
    price: 6000000,
  },
  {
    id: 18,
    name: "Logitec T650",
    image: require("../Assets/cursorcontroller/images2.jpg"),
    category: "Cursor Controller",
    price: 1200000,
  },
  {
    id: 19,
    name: "track pad",
    image: require("../Assets/cursorcontroller/images3.jpg"),
    category: "Cursor Controller",
    price: 3000000,
  },
  {
    id: 20,
    name: "track pad external",
    image: require("../Assets/cursorcontroller/images4.jpg"),
    category: "Cursor Controller",
    price: 1300000,
  },
];
